adj1=input("Enter a adjective:")
adj2=input("Enter another adjective:")
bird=input("Enter a bird name:")
room=input("Enter a room in house:")
past_verb=input("Enter a  past verb:")
verb=input("Enter a verb:")
relatives_name=input("Enter a name:")
liquid=input("Enter a liquid:")
ing_verb=input("Enter a verb with ing:")
body_part=input("Enter a body Part:")
plural_noun=input("Enter a plural noun:")
ing_verb1=input("Enter another verb with ing:")
noun=input("Enter a noun:")
print("It was a "+adj1+" ,cold November day. I woke up to the "+adj2+" smell of "+bird+" roasting in the "+room+" downstairs.")
print(" I "+past_verb+" down the stairs to see if i could help "+verb+" dinner. My mom said,\"See if "+relatives_name+" needs a fresh "+noun+" .\"")
print("So i carried a tray of glasses full of "+liquid+" into the "+ing_verb+" room.")
print("When i got there,I couldn\'t believe my "+body_part+" ! There were "+plural_noun+" " +ing_verb1+" on the "+noun+" !!\nHAHAHAHAHAHAHAHA")